vsock: Implement sibling VM communication
rust-vmm/vhost-device pull request #370
Opened 2023-06-19 20:51 UTC by techiepriyansh

Adds support for communication between sibling VMs that use the vhost-user-vsock devices from the same vhost-user-vsock application.

2023-06-22 09:04 UTC, stefano-garzarella requested changes
Good job!

I left several minor comments. I recommend that you add an example of how you tested the patch in the commit message.

Another thing I think we should put in is something to decide whether 2 VMs should communicate or not.
One idea would be to add a new "group" parameter to each VM and have only the VMs in the same "group" communicate.

Obviously we can do that later, but I wanted to tell you before I forget.

2023-06-22 09:06 UTC, stefano-garzarella commented
Ah I think we should extend the README and say if you add more VMs they can communicate with each other.

Another thing I have to check now that we have more VMs, is that the packets received from a VM have the right src_cid, otherwise one might impersonate another.

I think we didn't have this check before, but now we should since we have more VMs.

2023-06-22 15:44 UTC, germag commented on crates/vsock/src/thread_backend.rs
> +    fn create_from_vsock_packet<B: BitmapSlice>(pkt: &VsockPacket<B>) -> Result<Self> {
nit: usually, this type of constructors/factory methods are called just `from_` instead of `create_from_`

2023-06-23 08:12 UTC, techiepriyansh commented on crates/vsock/src/vhu_vsock_thread.rs
> +        Ok(used_any)
I am now using a boolean parameter to differentiate between `recv_pkt` and `recv_raw_vsock_pkt`. Should I use an enum instead?

2023-06-23 08:17 UTC, techiepriyansh commented on crates/vsock/src/main.rs
> +        let backend = Arc::new(VhostUserVsockBackend::new(config, None).unwrap());
I have now added a test (in the same test function) passing the map, but I don't know if it's really meaningful. What do you think?

2023-06-23 08:34 UTC, techiepriyansh commented
> I recommend that you add an example of how you tested the patch in the commit message.

For testing, I used https://github.com/stefanha/nc-vsock/blob/master/nc-vsock.c with this patch:
```
diff --git a/nc-vsock.c b/nc-vsock.c
index 1704151..beda0fc 100644
--- a/nc-vsock.c
+++ b/nc-vsock.c
@@ -146,6 +146,7 @@ static int vsock_connect(const char *cid_str, const char *port_str)
 	int port;
 	struct sockaddr_vm sa = {
 		.svm_family = AF_VSOCK,
+		.svm_flags = VMADDR_FLAG_TO_HOST,
 	};
 
 	cid = parse_cid(cid_str);
```

Should I mention all this in the commit message, or should I make a fork with this patch applied and then link to it?

2023-06-23 08:35 UTC, stefano-garzarella commented on crates/vsock/src/vhu_vsock_thread.rs
> +        Ok(used_any)
Yep, maybe enum is even better.

Another suggestion, I would remove `vsock` in the function/enum names, `raw_pkt` should be enough.

2023-06-23 08:42 UTC, stefano-garzarella commented
> > I recommend that you add an example of how you tested the patch in the commit message.
> 
> Should I mention all this in the commit message, or should I make a fork with this patch applied and then link to it?

Should be fine something like:

```
Tested with nc-vsock patched to set `.svm_flags = VMADDR_FLAG_TO_HOST`:
  host$ ./vhost-user-vsock .....
  
  vm1$ nc-vsock ...
  vm2$ nc-vsock ...
```

2023-06-23 09:02 UTC, techiepriyansh commented
I am getting a cargo audit error in the checks. Should I commit the rebuilt cargo lock file by running `cargo generate-lockfile` in this PR itself?

2023-06-23 10:23 UTC, techiepriyansh commented
> Do you have the same issue on the `main` branch?

Yes

> If it is the case, will be better to have another PR.

Okay

2023-06-23 10:42 UTC, techiepriyansh commented
I've created the PR fixing `cargo audit` errors over at #371.

2023-06-23 14:30 UTC, techiepriyansh commented
Rebased over main now that #371 has been merged.

2023-06-28 07:17 UTC, stefano-garzarella commented
@techiepriyansh the final result LGTM!

The only thing I'd suggest is to reorganize the commits, I'd move the new 2 commits, before the one that adds support for communication between multiple VMs, so we don't add code (e.g. `cid_map`) that we edit right after that.

2023-06-29 19:11 UTC, techiepriyansh commented
I've now moved the commit handling the single VM case same as multiple VMs before the commit implementing sibling VM communication. I've not moved the commit checking the packet source CID yet because I think it makes more sense to put it afterwards, but do let me know if I need to move it back too.

2023-06-30 07:25 UTC, stefano-garzarella commented
> I've now moved the commit handling the single VM case same as multiple VMs before the commit implementing sibling VM communication. I've not moved the commit checking the packet source CID yet because I think it makes more sense to put it afterwards, but do let me know if I need to move it back too.

LGTM!

2023-06-30 07:25 UTC, stefano-garzarella approved these changes

2023-07-03 05:59 UTC, vireshk approved these changes

2023-07-03 06:03 UTC, merged