Update Vhost-device-can dependency on socketcan and move it in the main workspace
rust-vmm/vhost-device pull request #760
Opened 2024-11-11 13:43 UTC by TimosAmpel

### Summary of the PR

This PR updates the socketcan-rs dependency of vhost-device-can device and moves it
on the main workspace.

Specifically by updating the socketcan-rs dependency to "v3.3.1" this PR solve the following
issues noted in the Cargo.toml of the vhost-device-can:
- socketcan-rs "v3.3.0" includes the following issue related to CANFD messages reception:
  - https://github.com/socketcan-rs/socketcan-rs/pull/61.
- If rust version "1.80" is used, the compiler might complain about "std::mem::size_of":
  - https://github.com/socketcan-rs/socketcan-rs/pull/72

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

2024-11-11 14:00 UTC, epilys requested changes
I think the two commits can be squashed, there's no reason to update Cargo.lock separately is there? 

Generally LGTM!

2024-11-11 14:00 UTC, epilys commented on vhost-device-can/LICENSE-APACHE
The symlinks need update since before they point two dirs upwards (`../../`) but now they have to point to `../` only.

2024-11-11 14:00 UTC, epilys commented on vhost-device-can/LICENSE-BSD-3-Clause
The symlinks need update since before they point two dirs upwards (`../../`) but now they have to point to `../` only.

2024-11-12 11:45 UTC, TimosAmpel commented on vhost-device-can/LICENSE-APACHE
Thanks @epilys, very good catch! I have also pushed a new commit fixing that issue also for vhost-device-console.

2024-11-12 11:48 UTC, TimosAmpel commented
> I think the two commits can be squashed, there's no reason to update Cargo.lock separately is there?
> 
> Generally LGTM!

Thanks for your review @epilys. Yes indeed I agree, I just merged everything in one commit.
SInce the last push I have also modified the coverage value under staging so the CI succeeds after moving
vhost-device-can, let me know if that's ok.

2024-11-12 13:07 UTC, epilys commented
@TimosAmpel looks good. you can drop the `Update licenses' symlinks for vhost-device-console` commit since it's part of <https://github.com/rust-vmm/vhost-device/pull/758>

2024-11-12 13:07 UTC, TimosAmpel commented on vhost-device-can/LICENSE-APACHE
Alright, sorry I missed that, I will delete that commit, rebase and push again then

2024-11-12 13:08 UTC, epilys requested changes
@TimosAmpel looks good. you can drop the `Update licenses' symlinks for vhost-device-console` commit since it's part of <https://github.com/rust-vmm/vhost-device/pull/758>

2024-11-12 13:10 UTC, epilys approved these changes

2024-11-12 13:15 UTC, epilys commented
@TimosAmpel fyi you can (and probably should since this is your device) leave reviews in https://github.com/rust-vmm/vhost-device/pull/758 and other PRs in general even if you're not a maintainer. They just don't count towards the "two approving reviews required" limit.

2024-11-12 13:23 UTC, TimosAmpel commented
> @TimosAmpel fyi you can (and probably should since this is your device) leave reviews in #758 and other PRs in general even if you're not a maintainer. They just don't count towards the "two approving reviews required" limit.

@epilys Thanks for pointing that out. Yes, I will review the changes done the next days

2024-11-14 03:29 UTC, vireshk approved these changes

2024-11-14 03:29 UTC, merged